# Generated by Django 2.1.1 on 2018-09-23 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('hash_id', models.CharField(blank=True, default='', max_length=100, primary_key=True, serialize=False)),
                ('nonce', models.IntegerField(blank=True, default=0, verbose_name='cantidad')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8)),
            ],
        ),
    ]
