# Generated by Django 2.1.1 on 2018-09-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='owners',
            name='nonce',
            field=models.IntegerField(blank=True, default=0, verbose_name='cantidad'),
        ),
    ]
