# Generated by Django 2.1.1 on 2018-09-21 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prev_hash_id', models.CharField(blank=True, default='', max_length=100, verbose_name='hash previo')),
                ('hash_id', models.CharField(blank=True, default='', max_length=100, verbose_name='hash')),
                ('timestamp', models.DateField(auto_now=True, verbose_name='fecha')),
                ('nonce', models.IntegerField(verbose_name='cantidad')),
            ],
            options={
                'ordering': ['hash_id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=3, max_digits=8, verbose_name='cantidad')),
                ('mined', models.BooleanField(default=False, verbose_name='minado')),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_receiver', to='owners.Owners', verbose_name='Receptor')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_sender', to='owners.Owners', verbose_name='Enviador')),
            ],
        ),
    ]
