# Generated by Django 2.1.1 on 2018-09-24 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(auto_now=True, verbose_name='fecha'),
        ),
    ]
