# Generated by Django 2.1.1 on 2018-09-24 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_transaction_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='prev_hash_id',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='hash previo'),
        ),
    ]
